server:
  port: 8888

spring:
  cloud:
    stream:
      bindings:
        rabbitmq2018:
          binder: rabbit
          destination: rabitDes01
        mns2018:
          binder: mns
          destination: mns-test-queue-name

  aliyun:
    mns:
      accountendpoint: http://{endpoint}/
      accesskeyid: {accesskeyid}
      accesskeysecret: {secretkeyid}